# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hashedname',
            field=models.BigIntegerField(default=0),
        ),
    ]
