# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_hashedname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hashedname',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
