# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170715_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='contactphone',
            field=models.CharField(default=8622285225, max_length=15),
            preserve_default=False,
        ),
    ]
